.travis.yml
samples/ImageSharp.Web.Sample/ImageSharp.Web.Sample.csproj
src/ImageSharp.Web/ImageSharp.Web.csproj
tests/ImageSharp.Web.Tests/ImageSharp.Web.Tests.csproj

Preventing MissingMethodException on EntityTagHeaderValue.ctor(string)
Fixes #2

Targetting netstandard2.0

---

src/ImageSharp.Web/DependencyInjection/ServiceCollectionExtensions.cs

Option configuration services shouldn't be singletons as they should be discarded once called.
Using TryAdd as calling AddImageSharpCore several times (common pattern) would otherwise overwrite custom options.

Refactor options registration

---

samples/ImageSharp.Web.Sample/Startup.cs
src/ImageSharp.Web/Caching/CachedInfo.cs
src/ImageSharp.Web/Caching/IImageCache.cs
src/ImageSharp.Web/Caching/PhysicalFileSystemCache.cs
src/ImageSharp.Web/DependencyInjection/ImageSharpCoreBuilderExtensions.cs
src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs
src/ImageSharp.Web/Resolvers/PhysicalFileSystemResolver.cs

THis PR adds the optional ability to the `PhysicalFileSystemCache` to check the source file for any changes since the last request. This means that someone can replace an image with an updated one with the same name and the cache will automatically update the cached result to match.
By default this is off since it adds overhead to the request. Turning the functionality on is performed in the following manner:
``` c#
services.AddImageSharpCore()
.SetCache(
provider => new PhysicalFileSystemCache(provider.GetRequiredService<IHostingEnvironment>())
{
Settings =
{
new KeyValuePair<string, string>( PhysicalFileSystemCache.Folder, PhysicalFileSystemCache.DefaultCacheFolder),
new KeyValuePair<string, string>( PhysicalFileSystemCache.CheckSourceChanged, "true")
}
});
```

PhysicalFileSystemCache can now choose to check the source for changes

---

src/ImageSharp.Web/Caching/PhysicalFileSystemCache.cs
src/ImageSharp.Web/Resolvers/PhysicalFileSystemResolver.cs

Fixes #10 Turns out we weren't Url decoding the request path before checking it using a FileInfo. 
No specific tests yet as we need to finish fleshing out the tests first.

UrlDecode request path

---

src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs

This is related to https://github.com/OrchardCMS/OrchardCore/issues/1472
A proposal to filter the commands dictionary before supplying it to the OnValidate option.

Add command filtering before OnValidate is called.

---

src/ImageSharp.Web/Helpers/FormatHelpers.cs
tests/ImageSharp.Web.Tests/Helpers/FormatHelpersTests.cs

This is related to https://github.com/OrchardCMS/OrchardCore/issues/1472
I've made some changes to the FormatHelpers.GetExtension method to make it "safer":
- At first it checks the query string for the "format" parameter, then it searches the path of the URI for a known file extension.
- It only matches an extension preceeded by a dot.
- It now correctly selects the most matching extension in case of multiple extensions with the same character sequence, for example "bm" and "bmp". Previously it would match "bm" even if the URI contained "bmp".

Improve/fix FormatHelpers.GetExtension URI parsing

---

samples/ImageSharp.Web.Sample/Startup.cs
src/ImageSharp.Web/Caching/CacheHash.cs
src/ImageSharp.Web/Caching/DoormanPool.cs
src/ImageSharp.Web/Caching/ICacheHash.cs
src/ImageSharp.Web/Caching/IImageCache.cs
src/ImageSharp.Web/Caching/PhysicalFileSystemCache.cs
src/ImageSharp.Web/DependencyInjection/ImageSharpConfiguration.cs
src/ImageSharp.Web/DependencyInjection/ImageSharpCoreBuilderExtensions.cs
src/ImageSharp.Web/DependencyInjection/ServiceCollectionExtensions.cs
src/ImageSharp.Web/FormattedImage.cs
src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs
src/ImageSharp.Web/Middleware/ImageSharpMiddlewareOptions.cs
src/ImageSharp.Web/Resolvers/PhysicalFileSystemResolver.cs
tests/ImageSharp.Web.Tests/Caching/CacheHashTests.cs
tests/ImageSharp.Web.Tests/ImageSharpTestServer.cs

This PR does several things
- Fixes #15 by adding a specific error message
- Adds `ICacheHash` and default implementation that allows users to generate their own file name hashing algorithm. 
- Replaced current hashing with simpler SHA256 implementation (this breaks current caches but speeds up hashing)
- Add `CachedNameLength` to our options. When using the default cache this allows increased nesting and reduction of collision probability.

Improve file resolving and caching

---

.travis.yml
ImageSharp.Web.sln
src/ImageSharp.Web/Commands/TypeConstants.cs
src/ImageSharp.Web/FormattedImage.cs
src/ImageSharp.Web/Helpers/FormatHelpers.cs
src/ImageSharp.Web/ImageSharp.Web.csproj
src/ImageSharp.Web/Processors/BackgroundColorWebProcessor.cs
src/ImageSharp.Web/Processors/FormatWebProcessor.cs
src/ImageSharp.Web/Processors/ResizeWebProcessor.cs
tests/ImageSharp.Web.Benchmarks/CacheHashBaseline.cs
tests/ImageSharp.Web.Benchmarks/Caching/CacheHashBenchmarks.cs
tests/ImageSharp.Web.Benchmarks/ImageSharp.Web.Benchmarks.csproj
tests/ImageSharp.Web.Benchmarks/MemoryConfig.cs
tests/ImageSharp.Web.Benchmarks/Program.cs
tests/ImageSharp.Web.Tests/Commands/CommandParserTests.cs

Reduces the allocation per hash generation from 2.48kb to 2.4kb.
Possible to reduce slightly further using .NET Core 2.1

Slightly more efficient hashing + Update dependencies

---

src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs

ICacheHash parameter null check fixed on ImageSharpMiddleware constructor.

ICacheHash parameter null check fixed

---

src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs
src/ImageSharp.Web/Providers/IImageProvider.cs
src/ImageSharp.Web/Providers/PhysicalFileSystemProvider.cs

This makes it possible for implementations of IImageProvider that rely on remote image sources to asynchronously create an IImageResolver.  This is important as it allows them to determine whether the requested image exists or not in an asynchronous manner prior to returning the IImageResolver.

Replace IImageProvider.Get() with GetAsync()

---

src/ImageSharp.Web/ImageMetadata.cs

Read metadata is returning date in local time. When parsing "o" format specifier, the formatted string should be parsed with `DateTimeStyles.RoundtripKind`. More info [here](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#the-round-trip-o-o-format-specifier)

Fix metadata read datetime to UTC

---

src/ImageSharp.Web/Caching/AsyncKeyLock.cs
src/ImageSharp.Web/Caching/Doorman.cs

This change addresses the race conditions identified in #56 by adding a RefCount property to the Doorman class and then using a SpinLock to serialize access to the Keys dictionary.  It also adds a pool so that unused doormen can be re-used in order to cut down on GC allocations and reduce the time spent holding the SpinLock.

Fix race-condition in AsyncKeyLock

---

.gitignore
src/ImageSharp.Web/Commands/QueryCollectionRequestParser.cs
src/ImageSharp.Web/Guard.cs
src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs
src/ImageSharp.Web/Middleware/ImageSharpMiddlewareOptions.cs

I profiled [Orchard Core](https://github.com/OrchardCMS/OrchardCore) as @sebastienros gave the idea. I saw that ImageSharp was doing some unnecessary processing as part of the pipeline when the request ended to be no-op on ImageSharp's behalf. I tweaked following bits:
* reduce usage of LINQ, which is always more expensive than "code nearer to the metal"
* change error handling to be more easy to inline (micro optimization)
* use concrete types as fields, no extra penalty from interface access
* split the actual work to `ProcessRequest` when actually needed
* don't parse in `OnParseCommands` when result is discarded

Improve ImageSharpMiddleware no-op case's performance

---

src/ImageSharp.Web/DependencyInjection/ImageSharpCoreBuilderExtensions.cs
tests/ImageSharp.Web.Tests/DependencyInjection/ServiceRegistrationExtensionsTests.cs

Following on from https://github.com/SixLabors/ImageSharp.Web/issues/62 this updates the `ImageSharpCoreBuilderExtensions` to also support removing registrations, when the registration occurred via a service factory.
I included a couple of new tests for implementation factory registration and removal

Update remove extensions to handle implementation factories

---

src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs

Ensures that we return early when there are no commands to process.

Return on no commands

---

src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs

There was an unfortunate problem in optimization PR which surfaced in OrchardCore. Commands were mutated with active iterator and that broke the contract. This fixes the problem and hopefully you could do yet another release to NuGet 🙏

Prevent concurrent modification when iterating request commands

---

src/ImageSharp.Web/Caching/PhysicalFileSystemCache.cs
src/ImageSharp.Web/ImageSharp.Web.csproj

Fixes https://github.com/SixLabors/ImageSharp.Web/issues/78
I've updated `PhysicalFileSystemCache` to create a `PhysicalFileProvider` from the `IHostingEnvironment.WebRootPath` to work around the issues some people are experiencing in development mode with core 3
It has meant taking a reference on `Microsoft.Extensions.FileProviders.Physical` but I think I've got the correct versions for both targets `netstandard1.4` and `netstandard2.0`, noting there is no released version of 1.1.2 which would match the other `netstandard1.4` targets

Create PhysicalFileProvider from Webroot

---

src/ImageSharp.Web.Providers.Azure/Providers/AzureBlobStorageImageProvider.cs
src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs
src/ImageSharp.Web/Providers/IImageProvider.cs
src/ImageSharp.Web/Providers/PhysicalFileSystemProvider.cs
src/ImageSharp.Web/Providers/ProcessingBehavior.cs
tests/ImageSharp.Web.Tests/DependencyInjection/MockImageProvider.cs

Addresses #77 
This exposes a setting on individual providers to determine whether they should continue processing an image when no commands are supplied. This is important for remote providers - such as the `AzureBlobStorageImageProvider` - as they are unable to fall back on the static files middleware to serve images.

Add a setting so providers can process images when no commands are supplied.

---

Directory.Build.targets
ImageSharp.Web.sln
README.md
ci-test.ps1
codecov.yml
src/ImageSharp.Web.Providers.Azure/Resolvers/AzureBlobStorageImageResolver.cs
src/ImageSharp.Web/ChunkedMemoryStream.cs
src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs
tests/Directory.Build.props
tests/Directory.Build.targets
tests/ImageSharp.Web.Tests/ChunkedMemoryStreamTests.cs
tests/coverlet.runsettings

- Exposes `ChunkedMemoryStream` as a public type.
- Ensures entire Azure Blob stream is copied before processing.

Copy Azure stream to prevent read errors

---

Directory.Build.targets
codecov.yml
src/ImageSharp.Web.Providers.Azure/ImageSharp.Web.Providers.Azure.csproj
src/ImageSharp.Web.Providers.Azure/Providers/AzureBlobStorageImageProvider.cs
src/ImageSharp.Web.Providers.Azure/Providers/AzureBlobStorageImageProviderOptions.cs
src/ImageSharp.Web.Providers.Azure/Resolvers/AzureBlobStorageImageResolver.cs
src/ImageSharp.Web/Caching/AsyncKeyLock.cs
src/ImageSharp.Web/Caching/PhysicalFileSystemCache.cs
src/ImageSharp.Web/ImageCacheMetadata.cs
src/ImageSharp.Web/Middleware/ImageContext.cs
src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs
tests/ImageSharp.Web.Tests/Actions/ActionTests.cs
tests/ImageSharp.Web.Tests/Caching/AsyncKeyLockTests.cs
tests/ImageSharp.Web.Tests/ImageSharp.Web.Tests.csproj
tests/ImageSharp.Web.Tests/ImageSharpTestServer.cs

- Updates the Azure SDK to the latest version.
- No longer attempts to create a container when none exists. (Don't throw, just let Azure throw)
- Removes all unneeded `ConfigureAwait(false)` calls.

Update Azure Blob SDK and cleanup

---

Directory.Build.targets
README.md
src/ImageSharp.Web/Caching/PhysicalFileSystemCache.cs
src/ImageSharp.Web/Commands/CommandParser.cs
src/ImageSharp.Web/Commands/Converters/ColorConverter.cs
src/ImageSharp.Web/Commands/TypeConstants.cs
tests/ImageSharp.Web.Tests/Commands/CommandParserTests.cs

Updates the shared infrastructure of the ImageSharp.Web project

Update shared infrastructure

---

src/ImageSharp.Web/Processors/ResizeWebProcessor.cs

When cropping without specifying explicit 'rxy' in the url, the CenterCoordinates will be set to PointF.Empty and the AnchorPositionMode.Center will be ignored because ResizeHelper checks for CenterCoordinates.HasValue.

AnchorPositionMode.Center is ignored when CenterCoordinates is Empty

---

ImageSharp.Web.sln
src/ImageSharp.Web.Providers.Azure/Providers/AzureBlobStorageImageProvider.cs
src/ImageSharp.Web.Providers.Azure/Providers/AzureBlobStorageImageProviderOptions.cs
tests/ImageSharp.Web.Tests/ImageSharpTestServer.cs

Replaces #82 by @agrigg  due to merge conflicts and churn.
It's now possible to configure multiple Azure Blob Containers for the provider. 
The provider will resolve containers in the following format.
```
/{CONTAINER_NAME}/{BLOB_FILENAME} 
```
Care has been taken to ensure that container name matching is exact when resolving the correct container to retrieve from so multiple containers beginning with the same prefix will be matched.
Configuration via the fluent API is as follows: 
```c#
.Configure<AzureBlobStorageImageProviderOptions>(options =>
{
options.BlobContainers.Add(new AzureBlobContainerClientOptions
{
ConnectionString = {AZURE_CONNECTION_STRING},
ContainerName = {AZURE_CONTAINER_NAME}
});
})
```

Add Support for Multiple Azure Connections and Containers.

---

src/ImageSharp.Web.Providers.Azure/Providers/AzureBlobStorageImageProvider.cs
src/ImageSharp.Web.Providers.Azure/Providers/AzureBlobStorageImageProviderOptions.cs
src/ImageSharp.Web.Providers.Azure/Resolvers/AzureBlobStorageImageResolver.cs
tests/ImageSharp.Web.Tests/ImageSharpTestServer.cs

Migrates the Azure Provider APIs to new `**.Azure` namespace to remove API docs conflict.

Move namespaces to fix docs conflict.

---

samples/ImageSharp.Web.Sample/ImageSharp.Web.Sample.csproj
src/ImageSharp.Web/Processors/BackgroundColorWebProcessor.cs
tests/ImageSharp.Web.Tests/Commands/CommandParserTests.cs

Bad type parameter passing for the background color processor. Fix #96

Pass correct type parameter to background color processor.

---

src/ImageSharp.Web.Providers.Azure/Providers/AzureBlobStorageImageProvider.cs
src/ImageSharp.Web.Providers.Azure/Resolvers/AzureBlobStorageImageResolver.cs
src/ImageSharp.Web/DependencyInjection/ImageSharpCoreBuilderExtensions.cs
src/ImageSharp.Web/DependencyInjection/ServiceCollectionExtensions.cs
src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs
tests/ImageSharp.Web.Tests/Actions/ActionTests.cs
tests/ImageSharp.Web.Tests/ImageSharpTestServer.cs

Simplifies the middleware workflow and removes the requirement for stream copying in individual providers.
Adds tests to ensure we handle cached and non-cached scenarios.

Simplify middleware workflow.

---

README.md
samples/ImageSharp.Web.Sample/Startup.cs
src/ImageSharp.Web/Caching/CacheHash.cs
src/ImageSharp.Web/DependencyInjection/ImageSharpBuilderExtensions.cs
src/ImageSharp.Web/DependencyInjection/ServiceCollectionExtensions.cs
src/ImageSharp.Web/FormatUtilities.cs
tests/ImageSharp.Web.Benchmarks/Caching/CacheHashBenchmarks.cs
tests/ImageSharp.Web.Tests/Caching/CacheHashTests.cs
tests/ImageSharp.Web.Tests/DependencyInjection/ServiceRegistrationExtensionsTests.cs
tests/ImageSharp.Web.Tests/Helpers/FormatUtilitiesTests.cs

- Removes the `AddImageSharpCore` extensions. We don't need them anymore and they're confusing.
- Removes weird registration of services via options sub properties.
- Adds `ClearProviders` and `ClearProcessors` to allow simplified reset of registered services.
- Use `ArrayPool` for supplying buffers for hashing long strings.
- Fix missing .Web suffix from readme.

Simplify Dependency Injection

---

global.json
src/Directory.Build.props
src/Directory.Build.targets
src/ImageSharp.Web/DependencyInjection/ImageSharpBuilderExtensions.cs

.NET 5 bring a native InternalVisibleTo target implementation that is incompatible with our current implementation. The fix is simple, update our property to use the same Key attribute rather than PublicKey.
Tested using Visual Studio 16.8.0 Preview 2.1 and .NET 5 SDK 5.0.100-preview.8.20417.9
cc/ @sandcastle

Fix compatibility with NET 5 SDK InternalsVisibleTo

---

.github/workflows/build-and-test.yml
samples/ImageSharp.Web.Sample/wwwroot/index.html
src/ImageSharp.Web/FormatUtilities.cs
tests/ImageSharp.Web.Tests/Processing/AzureBlobStorageCacheServerTests.cs
tests/ImageSharp.Web.Tests/Processing/PhysicalFileSystemCacheServerTests.cs

Adding tests to prove `AsyncKeyLock` works and that #118 was due to a testing issue.

Add Parallel Identical Query Tests.

---

src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs

Proposes replacing the `AsyncKeyLock` with an implementation based around `ConcurrentDictionary`.
Note: I have not removed the `AsyncKeyLock` code or related test code.
Test coverage from the Integration Tests.

Lock free Read/Write Identical Request Implementation

---

samples/ImageSharp.Web.Sample/Startup.cs
samples/ImageSharp.Web.Sample/wwwroot/index.html
src/ImageSharp.Web/DependencyInjection/ServiceCollectionExtensions.cs
src/ImageSharp.Web/FormattedImage.cs
src/ImageSharp.Web/Middleware/ImageProcessingContext.cs
src/ImageSharp.Web/Processors/FormatWebProcessor.cs
src/ImageSharp.Web/Processors/JpegQualityWebProcessor.cs
tests/ImageSharp.Web.Tests/DependencyInjection/ServiceRegistrationExtensionsTests.cs
tests/ImageSharp.Web.Tests/Processors/FormattedImageTests.cs
tests/ImageSharp.Web.Tests/Processors/JpegQualityWebProcessorTests.cs
tests/ImageSharp.Web.Tests/TestUtilities/AzureBlobStorageCacheTestServerFixture.cs
tests/ImageSharp.Web.Tests/TestUtilities/PhysicalFileSystemCacheTestServerFixture.cs

Introduces the ability to set the quality of jpegs per request. Commands are sent in the following manner.
See Discussion #123 for reference.
```
{PATH_TO_YOUR_IMAGE}?quality=50
{PATH_TO_YOUR_IMAGE}?format=jpg&quality=50
```
As we introduce image other image formats that support variable quality we can create format specific quality parsers that will not conflict with this one allowing the sharing of the same command key.

Allow the ability to set the quality of jpegs.

---

src/ImageSharp.Web/Caching/PhysicalFileSystemCache.cs
src/ImageSharp.Web/Caching/PhysicalFileSystemCacheOptions.cs
tests/ImageSharp.Web.Tests/Caching/PhysicialFileSystemCacheTests.cs
tests/ImageSharp.Web.Tests/ImageSharp.Web.Tests.csproj

Adding a new Option for the cache implementation. Now the CacheRoot can be set to an different folder than the webroot

Add an option to enable setting a different CacheRoot

---

.editorconfig
.gitattributes
Directory.Build.props
Directory.Build.targets
before.ImageSharp.Web.sln.targets
samples/Directory.Build.props
samples/Directory.Build.targets
src/Directory.Build.props
src/Directory.Build.targets
src/ImageSharp.Web.Providers.Azure/ImageSharp.Web.Providers.Azure.csproj
src/ImageSharp.Web/ImageSharp.Web.csproj
src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs
tests/Directory.Build.props
tests/Directory.Build.targets
tests/ImageSharp.Web.Benchmarks/MemoryConfig.cs
tests/ImageSharp.Web.Tests/Caching/PhysicialFileSystemCacheTests.cs
tests/ImageSharp.Web.Tests/Commands/CommandParserTests.cs
tests/ImageSharp.Web.Tests/ImageSharp.Web.Tests.csproj

Fixes https://github.com/SixLabors/ImageSharp.Web/issues/140
Simple option. 
Merge them into one cache, and treat them as tuples.
Other option is to cache it locally inside `IImageCacheResolver` so that subsequent calls retrieve the same instance.
But I think this involves less changes.

Fix missing cache lookups

---

src/ImageSharp.Web.Providers.Azure/ImageSharp.Web.Providers.Azure.csproj
src/ImageSharp.Web/ImageSharp.Web.csproj

We were missing config settings following the upgrade I did in #141 
Successful packing has been tested and confirmed locally.

Fix DotNet Pack 

---

src/ImageSharp.Web/Middleware/LoggerExtensions.cs

Fixes #143
Error is too intrusive and these events are too common, the event log can then fill up quickly. Moving it to `Debug` since this is what aspnet uses for the standard static file provider on these events.

Adapting log level when files are not found

---

src/ImageSharp.Web/DependencyInjection/ImageSharpBuilderExtensions.cs

Obsoletes `SetMemoryAllocator` (from https://github.com/SixLabors/ImageSharp.Web/discussions/152) - that's caused me confusion in the past before too :)
I was going to remove the comments, but then stylecop doesn't like it. 
Could update them to mention the obsolete message if preferable?
Could also just remove them, instead of obsolete...

Obsolete SetMemoryAllocator builder extensions

---

src/ImageSharp.Web/FormatUtilities.cs

Avoid some of the string allocations in GetExtensionFromUri, and it's also faster.
| Method |     Mean |    Error |   StdDev | Ratio | RatioSD |  Gen 0 | Allocated |
|------- |---------:|---------:|---------:|------:|--------:|-------:|----------:|
|    Old | 74.75 us | 0.813 us | 0.761 us |  1.00 |    0.00 | 2.0752 |     18 KB |
|    New | 60.40 us | 1.139 us | 1.119 us |  0.81 |    0.02 | 1.2207 |     11 KB |
|    NewV2 | 57.30 us | 0.905 us | 0.846 us |  0.77 | 0.02 | 0.9766 |      8 KB |
|    NewV3 | 56.38 us | 0.348 us | 0.325 us |  0.77 | 0.02 |  0.3662 |      3 KB |

Avoid most allocations in GetExtensionFromUri

---

src/ImageSharp.Web/DependencyInjection/ServiceCollectionExtensions.cs
src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs
src/ImageSharp.Web/Synchronization/AsyncKeyLock.cs
src/ImageSharp.Web/Synchronization/AsyncKeyReaderWriterLock.cs
src/ImageSharp.Web/Synchronization/AsyncLock.cs
src/ImageSharp.Web/Synchronization/AsyncReaderWriterLock.cs
src/ImageSharp.Web/Synchronization/RefCountedConcurrentDictionary.cs
tests/ImageSharp.Web.Benchmarks/Synchronization/AsyncLockBenchmarks.cs
tests/ImageSharp.Web.Benchmarks/Synchronization/RefCountedConcurrentDictionaryBenchmarks.cs
tests/ImageSharp.Web.Tests/Synchronization/AsyncKeyLockTests.cs
tests/ImageSharp.Web.Tests/Synchronization/AsyncKeyReaderWriterLockTests.cs
tests/ImageSharp.Web.Tests/Synchronization/AsyncLockTests.cs
tests/ImageSharp.Web.Tests/Synchronization/AsyncReaderWriterLockTests.cs
tests/ImageSharp.Web.Tests/Synchronization/RefCountedConcurrentDictionaryTests.cs

Per the discussion in #193, this PR restores the ability to effectively disable the caching logic through the use of a "NullCache".  The most important part of this change is restoring the ability to stream the response directly from the processed image output, which is how it worked before v1.0.3.  In v1.0.3, the `WriterWorkers` pattern was introduced, and a side effect of that change was that the response was now _always_ streamed from the cache, which broke the ability to use a NullCache.  To address this, I removed the `ReadWorkers`/`WriterWorkers` stuff and replaced it with a more standard reader/writer locking pattern using a synchronization library ported from my company's codebase.  This made it so that the processed image stream could remain available beyond the section of code …

Restore ability to use null cache

---

src/ImageSharp.Web/FormatUtilities.cs
src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs
src/ImageSharp.Web/Processors/FormatWebProcessor.cs
tests/ImageSharp.Web.Tests/Helpers/FormatUtilitiesTests.cs

Fixes #195 
Ensures that we don't attempt to process an image request containing an invalid format command.

Ensure invalid format commands don't get processed.

---

src/ImageSharp.Web.Providers.Azure/Resolvers/AzureBlobStorageCacheResolver.cs
src/ImageSharp.Web.Providers.Azure/Resolvers/AzureBlobStorageImageResolver.cs

`DownloadAsync` is obsolete and inefficient since it downloads the whole blob + content. `OpenReadAsync` streams the blob content directly as the blob is read.

Use more efficient (and not obsolete) download method for Azure Blobs.

---

ImageSharp.Web.sln
appveyor.yml
src/ImageSharp.Web.Providers.AWS/ImageSharp.Web.Providers.AWS.csproj
src/ImageSharp.Web.Providers.AWS/Providers/AWSS3StorageImageProvider.cs
src/ImageSharp.Web.Providers.AWS/Providers/AWSS3StorageImageProviderOptions.cs
src/ImageSharp.Web.Providers.AWS/Resolvers/AWSS3FileSystemResolver.cs
src/Shared/AssemblyInfo.Common.cs

Hi,
We are internally using our own provider based on some of our own libraries. I am looking to port this to the latest version of `ImageSharp.Web` and remove our custom libraries. Is this something you would be interested in supporting in the library?
For testing internally we use [Minio](https://min.io) which I think would fit with how you are testing Azure Blob Storage.
Cheers,
Andrew

AWS S3 Provider

---

samples/ImageSharp.Web.Sample/Startup.cs
src/ImageSharp.Web/Caching/PhysicalFileSystemCache.cs
src/ImageSharp.Web/Caching/PhysicalFileSystemCacheOptions.cs
src/ImageSharp.Web/Caching/SHA256CacheHash.cs
src/ImageSharp.Web/DependencyInjection/ServiceCollectionExtensions.cs
src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs
src/ImageSharp.Web/Middleware/ImageSharpMiddlewareOptions.cs
tests/ImageSharp.Web.Benchmarks/Caching/CacheHashBenchmarks.cs
tests/ImageSharp.Web.Benchmarks/Caching/StringJoinBenchmarks.cs
tests/ImageSharp.Web.Tests/Caching/CacheHashTests.cs
tests/ImageSharp.Web.Tests/Caching/PhysicialFileSystemCacheTests.cs
tests/ImageSharp.Web.Tests/DependencyInjection/ServiceRegistrationExtensionsTests.cs

This is my second try to separate the cache hash length and folder depth as discussed in https://github.com/SixLabors/ImageSharp.Web/discussions/210, but without introducing a new option to keep creating backwards compatible cache file paths as done in https://github.com/SixLabors/ImageSharp.Web/pull/212.
In ImageSharp.Web v1 the folder depth is using the same value as the cache hash (with a default of 12), so the nested folders contain all characters from the file name. With this new implementation, it removes the characters used for the folders from the file name (to generate shorter file paths), but this would leave no characters left for the actual file name when these values are equal: `027ee1e815be.meta` would result in `0/2/7/e/e/1/e/8/1/5/b/e/.meta`. In this case, the …

Add CacheFolderDepth option and create shorter file names

---

src/Directory.Build.targets
src/ImageSharp.Web/Caching/LegacyV1CacheKey.cs
src/ImageSharp.Web/Caching/PhysicalFileSystemCache.cs
src/ImageSharp.Web/Caching/PhysicalFileSystemCacheOptions.cs
src/ImageSharp.Web/DependencyInjection/ImageSharpBuilderExtensions.cs
src/ImageSharp.Web/Middleware/ImageSharpMiddlewareOptions.cs
src/ImageSharp.Web/Providers/PhysicalFileSystemProvider.cs
src/ImageSharp.Web/Providers/PhysicalFileSystemProviderOptions.cs
tests/ImageSharp.Web.Tests/Caching/PhysicialFileSystemCacheTests.cs
tests/ImageSharp.Web.Tests/Providers/PhysicalFileSystemProviderTests.cs

This PR decouples the `PhysicalFileSystemProvider ` from the environment `WebRootFileProvider` allowing it to work independently bringing greater freedom for source image storage within the physical file system. It should be none breaking since it defaults to the existing source location when the new `PhysicalFileSystemProviderOptions.ProviderRootPath` property is not set.
See https://github.com/SixLabors/ImageSharp.Web/discussions/204#discussioncomment-2055878 for reference. 
I've additionally done a little required cleanup.

Decouple PhysicalFileSystemProvider from WebRootFileProvider

---

samples/ImageSharp.Web.Sample/Startup.cs
src/ImageSharp.Web/DependencyInjection/ServiceCollectionExtensions.cs
src/ImageSharp.Web/Processors/AutoOrientWebProcessor.cs
tests/ImageSharp.Web.Tests/Processors/AutoOrientWebProcessorTests.cs

See #191 for the relevant discussion. Adds a new `AutoOrientWebProcessor` which orients images to match an EXIF orientation of TopLeft

Add AutoOrientWebProcessor

---

.github/workflows/build-and-test.yml
src/Directory.Build.targets
src/ImageSharp.Web/ImageSharp.Web.csproj
src/ImageSharp.Web/Processors/ResizeWebProcessor.cs
tests/ImageSharp.Web.Tests/Processors/ResizeWebProcessorTests.cs

In addition to #215 we need the ability to resize images containing EXIF orientation metadata that specifies rotation based upon the users [observed expectation](https://twitter.com/James_M_South/status/1489219049532067842) without updating the EXIF metadata.
This PR updates the `ResizeWebProcessor` to swap dimensions parsed from command when a value indicating EXIF rotation is detected. This behavior can be turned off per request by passing the command `orient=false` (_Note I've deliberately not used an `r` prefix to make this more reusable for other potential transforming processors_).
cc\ @ronaldbarendse

Respect EXIF orientation when resizing

---

src/ImageSharp.Web.Providers.AWS/AmazonS3ClientFactory.cs
src/ImageSharp.Web.Providers.AWS/Caching/AWSS3StorageCache.cs
src/ImageSharp.Web.Providers.AWS/Caching/AWSS3StorageCacheOptions.cs
src/ImageSharp.Web.Providers.AWS/IAWSS3BucketClientOptions.cs
src/ImageSharp.Web.Providers.AWS/Providers/AWSS3StorageImageProviderOptions.cs
src/ImageSharp.Web.Providers.Azure/Caching/AzureBlobStorageCacheOptions.cs
src/ImageSharp.Web.Providers.Azure/IAzureBlobContainerClientOptions.cs
src/ImageSharp.Web.Providers.Azure/Providers/AzureBlobStorageImageProviderOptions.cs
tests/ImageSharp.Web.Tests/TestUtilities/AWSS3StorageCacheTestServerFixture.cs

While the options types share the same properties, it's important to maintain separate options classes to allow further extensibility and simplify json configuration.

Separate AWS cache options and normalize implementations

---

src/ImageSharp.Web/FormattedImage.cs
src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs

While debugging a memory dump taken during an outage of our production image processing servers, we discovered that nearly all of the thread pool worker threads were blocked waiting on network IO loading source image data, which led to thread pool starvation that was preventing any async work from executing.  This PR addresses the source of the problem by replacing the synchronous `Image.Load()` call with the equivalent async call.

Load source images asynchronously to prevent thread pool exhaustion

---

.github/CONTRIBUTING.md
samples/ImageSharp.Web.Sample/wwwroot/Landscape_0.jpg
samples/ImageSharp.Web.Sample/wwwroot/Landscape_1.jpg
samples/ImageSharp.Web.Sample/wwwroot/Landscape_2.jpg
samples/ImageSharp.Web.Sample/wwwroot/Landscape_3.jpg
samples/ImageSharp.Web.Sample/wwwroot/Landscape_4.jpg
samples/ImageSharp.Web.Sample/wwwroot/Landscape_5.jpg
samples/ImageSharp.Web.Sample/wwwroot/Landscape_6.jpg
samples/ImageSharp.Web.Sample/wwwroot/Landscape_7.jpg
samples/ImageSharp.Web.Sample/wwwroot/Landscape_8.jpg
samples/ImageSharp.Web.Sample/wwwroot/Portrait_0.jpg
samples/ImageSharp.Web.Sample/wwwroot/Portrait_1.jpg
samples/ImageSharp.Web.Sample/wwwroot/Portrait_2.jpg
samples/ImageSharp.Web.Sample/wwwroot/Portrait_3.jpg
samples/ImageSharp.Web.Sample/wwwroot/Portrait_4.jpg
samples/ImageSharp.Web.Sample/wwwroot/Portrait_5.jpg
samples/ImageSharp.Web.Sample/wwwroot/Portrait_6.jpg
samples/ImageSharp.Web.Sample/wwwroot/Portrait_7.jpg
samples/ImageSharp.Web.Sample/wwwroot/Portrait_8.jpg
samples/ImageSharp.Web.Sample/wwwroot/index.html
src/Directory.Build.targets
src/ImageSharp.Web/FormattedImage.cs
src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs
src/ImageSharp.Web/Processors/ResizeWebProcessor.cs
tests/ImageSharp.Web.Tests/Processors/ResizeWebProcessorTests.cs

Following on from #217  This PR updates `ResizeWebProcessor` to correctly handle `XY` and `Anchor` commands when processing EXIF orientated images.
There's a lot of work involved in handling this with most of the logic based upon some of the work upstream in ImageSharp when normalizing orientation values. The following [image](https://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/) will help explain the affect on an image each rotation value has.
cc @ronaldbarendse

Apply updates to XY and Anchor positions based on EXIF metadata

---

src/ImageSharp.Web/Middleware/ImageContext.cs
src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs

Allows the runtime deletion of cached images by handling any exceptions thrown during resolving the cached image. Fix #239 
If an exception is thrown we do a complete run through of the processing again to ensure that any changes to both the source and image are captured. If an issue still occurs we'll log and rethrow.
CC @ronaldbarendse

Allow runtime physical deletion of cached images

---

src/ImageSharp.Web/Providers/FileProviderImageProvider.cs
src/ImageSharp.Web/Providers/WebRootImageProvider.cs
src/ImageSharp.Web/Resolvers/FileProviderImageResolver.cs

This adds a `FileProviderImageProvider` and `WebRootImageProvider`, following the pattern mentioned in https://github.com/umbraco/Umbraco-CMS/pull/12185#discussion_r838138281. This is basically a simplified version of PR https://github.com/SixLabors/ImageSharp.Web/pull/207, but these `IImageProvider`s are now included as additional, non-default implementations.
This would allow users to easily switch from the default `PhysicalFileSystemProvider` to the `WebRootImageProvider` by using:
```c#
services.AddImageSharp()
.RemoveProvider<PhysicalFileSystemProvider>() // or .ClearProviders()
.AddProvider<WebRootImageProvider>();
```

Add FileProviderImageProvider and WebRootImageProvider 

---

src/ImageSharp.Web/DependencyInjection/ImageSharpBuilderExtensions.cs
tests/ImageSharp.Web.Tests/DependencyInjection/ServiceRegistrationExtensionsTests.cs

Adds the ability to insert an `IImageProvider` or factory into the provider collection. This reduces boilerplate code when adding multiple providers.

Add InsertProvider extensions and tests

---

samples/ImageSharp.Web.Sample/Startup.cs
src/ImageSharp.Web/DependencyInjection/ServiceCollectionExtensions.cs
src/ImageSharp.Web/Processors/AutoOrientWebProcessor.cs
src/ImageSharp.Web/Processors/WebProcessingExtensions.cs
tests/ImageSharp.Web.Tests/Processors/AutoOrientWebProcessorTests.cs

As discussed in #259: This PR re-adds `AutoOrientWebProcessor`

Re-add AutoOrientWebProcessor

---

src/ImageSharp.Web/Processors/QualityWebProcessor.cs

Update QualityWebProcessor.cs docs

---

src/ImageSharp.Web.Providers.AWS/AmazonS3ClientFactory.cs

Simply adding the optional `AuthenticationRegion` property to the `AmazonS3Config`.
https://github.com/SixLabors/ImageSharp.Web/issues/262

Added AuthenticationRegion to AmazonS3Client Endpoint based clients

---

src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs

Pass the missed `true` parameter to `the Invoke` method to allow retrying a command while allowing a short-circuit.
See #257 for a reference.

Fix infinite loop on cache file read error.

---

src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs

As previously [identified](https://github.com/SixLabors/ImageSharp.Web/pull/250/files#r857755086) using only the token as a cache key opens the potential for abuse of the caching mechanism. PR #256 was opened to remove that cache. 
I would consider removing the cache with current target frameworks to be too expensive given the large overhead of  HMAC generation so have replaced that PR with an implementation that uses the full encoded URL as the key. 
The cache key generation method causes low allocations due to the underlying usage of [`string.Create`](https://github.com/dotnet/aspnetcore/issues/28906) so I would consider it acceptable for now. For .NET 6 we can likely remove the cache in it's entirety due to the much improved reusable hashing methods available to that framework.

Use full URl as HMAC cache key

---

src/ImageSharp.Web.Providers.AWS/Providers/AWSS3StorageImageProvider.cs

…sts in a S3 Bucket.
We don't need the `ListBucket` permission when accessing the S3 bucket. We will always know the key we want to access, but the side effect is we are getting a Forbidden from the S3 bucket, probably to prevent bucket enumeration. I think it's safe to assume that the Key doesn't exist.

Added a check when forbidden is returned from S3 bucket

---

src/Directory.Build.targets
src/ImageSharp.Web.Providers.AWS/Caching/AWSS3StorageCache.cs
src/ImageSharp.Web/AsyncHelper.cs
src/ImageSharp.Web/Caching/UriAbsoluteCacheKey.cs
src/ImageSharp.Web/Caching/UriAbsoluteLowerInvariantCacheKey.cs
src/ImageSharp.Web/CaseHandlingUriBuilder.cs
src/ImageSharp.Web/CommandHandling.cs
src/ImageSharp.Web/Commands/PresetOnlyQueryCollectionRequestParser.cs
src/ImageSharp.Web/Commands/QueryCollectionRequestParser.cs
src/ImageSharp.Web/DependencyInjection/ServiceCollectionExtensions.cs
src/ImageSharp.Web/FormatUtilities.cs
src/ImageSharp.Web/ImageSharp.Web.csproj
src/ImageSharp.Web/ImageSharpRequestAuthorizationUtilities.cs
src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs
src/ImageSharp.Web/PathUtilities.cs
tests/ImageSharp.Web.Tests/Helpers/CaseHandlingUriBuilderTests.cs
tests/ImageSharp.Web.Tests/TestUtilities/AuthenticatedServerTestBase.cs
tests/ImageSharp.Web.Tests/TestUtilities/ServerTestBase.cs

Adds a new type `ImageSharpRequestAuthorizationUtilities` which completes the HMAC story, allowing developers to create tokens directly using the functions defined in the middleware options.

Add Authorization Utilitites

---

.github/workflows/build-and-test.yml
src/ImageSharp.Web.Providers.AWS/ImageSharp.Web.Providers.AWS.csproj
src/ImageSharp.Web.Providers.Azure/ImageSharp.Web.Providers.Azure.csproj
src/ImageSharp.Web/Caching/PhysicalFileSystemCache.cs
src/ImageSharp.Web/ImageSharp.Web.csproj
src/ImageSharp.Web/ImageSharpRequestAuthorizationUtilities.cs
src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs
src/ImageSharp.Web/Providers/PhysicalFileSystemProvider.cs
src/ImageSharp.Web/Providers/WebRootImageProvider.cs
src/ImageSharp.Web/Synchronization/RefCountedConcurrentDictionary.cs
tests/ImageSharp.Web.Benchmarks/ImageSharp.Web.Benchmarks.csproj
tests/ImageSharp.Web.Tests/ImageSharp.Web.Tests.csproj
tests/ImageSharp.Web.Tests/TestUtilities/AWSS3StorageImageProviderFactory.cs
tests/ImageSharp.Web.Tests/TestUtilities/AzureBlobStorageImageProviderFactory.cs

See #284 (Dependabot)
We have a security issue in the Azure Dependency and are unable to upgrade to mitigate the issue without removing support for .NET Core 2.. Since that target framework is long obsolete I've chosen to do this without a major update. The next version will be v2.1.0

Drop .NET Core 2.1 to fix Azure dependency security issue

---

src/ImageSharp.Web.Providers.AWS/AmazonS3ClientFactory.cs
src/ImageSharp.Web.Providers.AWS/Caching/AWSS3StorageCacheOptions.cs
src/ImageSharp.Web.Providers.AWS/IAWSS3BucketClientOptions.cs
src/ImageSharp.Web.Providers.AWS/Providers/AWSS3StorageImageProviderOptions.cs
tests/ImageSharp.Web.Tests/TestUtilities/AWSS3StorageCacheTestServerFixture.cs
tests/ImageSharp.Web.Tests/TestUtilities/TestConstants.cs

Most configurations of the S3Client can be set via environment variable, but it is not the case for the Timeout settings. I've only added a config and forwarded it.

Aws s3 client timeout

---

README.md

Fixed an issue with the build status shield in README.md

Fixed build status shield

---

src/ImageSharp.Web/Processors/ResizeWebProcessor.cs

Adds the ability to specify the targetrectangle in the commands. As asked in #302

Add Parsing of TargetRectangle to ResizeWebProcessor

---

src/ImageSharp.Web.Providers.AWS/Providers/AWSS3StorageImageProvider.cs
src/ImageSharp.Web.Providers.AWS/Resolvers/AWSS3StorageImageResolver.cs

When the image is resolved we validate if it exists with the method `KeyExists`. To validate this the methods fetch all the object metadata, if it fails it's considered not existent, but the result of that query isn't used.
This PR keeps the result and pass it to the AWS S3 image resolver.
I added an optional parameter for that metadata, in case the resolver needs to be build it elsewhere. If the metadata is not provided, it will fetch it like it used to.
Since I had overlapped change with https://github.com/SixLabors/ImageSharp.Web/pull/312, I included the change of those files in my PR to limit the conflicts and use the nullable options ;)

Updated the `KeyExists` from aws to keep the response metadata in the image resolver

---

src/ImageSharp.Web.Providers.AWS/AmazonS3ClientFactory.cs
src/ImageSharp.Web.Providers.AWS/Caching/AWSS3StorageCache.cs
src/ImageSharp.Web.Providers.AWS/Caching/AWSS3StorageCacheOptions.cs
src/ImageSharp.Web.Providers.AWS/IAWSS3BucketClientOptions.cs
src/ImageSharp.Web.Providers.AWS/Providers/AWSS3StorageImageProvider.cs
src/ImageSharp.Web.Providers.AWS/Providers/AWSS3StorageImageProviderOptions.cs
src/ImageSharp.Web.Providers.AWS/Resolvers/AWSS3StorageCacheResolver.cs
src/ImageSharp.Web.Providers.AWS/Resolvers/AWSS3StorageImageResolver.cs

Remove nullable disable from aws

---

src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs
src/ImageSharp.Web/Middleware/ImageSharpMiddlewareOptions.cs
tests/ImageSharp.Web.Tests/TestUtilities/TestServerFixture.cs

Removes the copy-only pipeline for images without commands to fix #316

Use a single pipeline for images.

---

src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs
src/ImageSharp.Web/Middleware/ImageSharpMiddlewareOptions.cs
tests/ImageSharp.Web.Tests/TestUtilities/TestServerFixture.cs

The current `OnBeforeLoadAsync` delegate is useless as `DecoderOptions` properties are init-only. This PR includes an emergency breaking change which updates the method to return options themselves.

Fix DecoderOptions handler.

---

src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs
src/ImageSharp.Web/Middleware/ImageSharpMiddlewareOptions.cs
src/ImageSharp.Web/RequestAuthorizationUtilities.cs
tests/ImageSharp.Web.Tests/TestUtilities/AsyncHelper.cs
tests/ImageSharp.Web.Tests/TestUtilities/AuthenticatedServerTestBase.cs
tests/ImageSharp.Web.Tests/TestUtilities/ServerTestBase.cs

Removing the extremely performance harming async HMAC generation utilities from both `ImageSharpMiddlewareOptions` and `RequestAuthorizationUtilities`
See https://github.com/umbraco/Umbraco-CMS/pull/14364 for more information.
cc @nikolajlauridsen  @bergmania  @ronaldbarendse

Remove async HMAC operations.

---

src/ImageSharp.Web/HMACUtilities.cs

As recommended by Microsoft (ref: https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1850  
and https://github.com/dotnet/runtime/issues/40579) we should favor the one-shot `HashData` over the `ComputeHash` methods whilst hashing HMAC hashes.
I've modified the source code and ran some benchmarks, the performance gain is minimal, but its still there:
```
|   Method |      Job |  Runtime | sizeKey | sizeInput |     Mean |    Error |   StdDev |   Gen0 | Allocated |
|--------- |--------- |--------- |-------- |---------- |---------:|---------:|---------:|-------:|----------:|
| Instance | .NET 6.0 | .NET 6.0 |      64 |        96 | 581.8 ns | 11.36 ns | 16.29 ns | 0.0420 |     536 B |
|  OneShot | .NET 6.0 | .NET 6.0 |      64 |        96 | 356.7 ns |  7.15 ns …
```

Use HMAC one-shot methods instead of instances

---

NuGet.Config
src/ImageSharp.Web/ExifOrientationUtilities.cs
src/ImageSharp.Web/FormattedImage.cs
src/ImageSharp.Web/ImageSharp.Web.csproj
src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs
src/ImageSharp.Web/Processors/AutoOrientWebProcessor.cs
src/ImageSharp.Web/Processors/BackgroundColorWebProcessor.cs
src/ImageSharp.Web/Processors/QualityWebProcessor.cs
src/ImageSharp.Web/Processors/ResizeWebProcessor.cs
src/ImageSharp.Web/Resampler.cs
src/ImageSharp.Web/TagHelpers/ImageTagHelper.cs

I need a fix in the 3.1 releases, sadly the alpha version of the `.Web` isn't compatible with the 3.1 release yet. I created this branch to fix the `using` in the `.Web` package.
- Added Feedz.io source for alpha builds
- Updated some using to work with 3.1 releases

3.1 release compatibility 

---

src/ImageSharp.Web.Providers.AWS/Caching/AWSS3StorageCache.cs
src/ImageSharp.Web.Providers.AWS/Caching/AWSS3StorageCacheOptions.cs
src/ImageSharp.Web.Providers.Azure/Caching/AzureBlobStorageCache.cs
src/ImageSharp.Web.Providers.Azure/Caching/AzureBlobStorageCacheOptions.cs
tests/ImageSharp.Web.Tests/Processing/AWSS3StorageCacheCacheFolderServerTests.cs
tests/ImageSharp.Web.Tests/Processing/AzureBlobStorageCacheCacheFolderServerTests.cs
tests/ImageSharp.Web.Tests/TestUtilities/AWSS3StorageCacheCacheFolderTestServerFixture.cs
tests/ImageSharp.Web.Tests/TestUtilities/AzureBlobStorageCacheCacheFolderTestServerFixture.cs
tests/ImageSharp.Web.Tests/TestUtilities/TestConstants.cs

For multi-tenancy scenarios and for feature parity with `PhysicalFileSystemCache`, this PR adds a `CacheFolder` configuration for the Azure and AWS Image Caches
Please see https://github.com/SixLabors/ImageSharp.Web/discussions/351 for more details, especially the rationale.
There are two things I'm unsure about, please advise:
1. Tests: My usual approach in such cases would be to turn the test into a `Theory` with input parameters, and run the test once without setting `CacheFolder`, and then once with it. In this test suite, I don't really see how to approach this; I could add another class like `AzureBlobStorageCacheTestServerFixture` where the new property is set, but that seems like the wrong approach. Same for `AWSS3StorageCacheTestServerFixture`. What should I do? I've run the …

Cache folder configuration for Azure and AWS Image Caches (Lombiq Technologies: OCORE-136)

---

src/ImageSharp.Web/ImageSharp.Web.csproj

Updates ImageSharp to version v3.1.4 Fixes #364

Update ImageSharp to v3.1.4

---

samples/ImageSharp.Web.Sample/Pages/IndexModel.cs
src/ImageSharp.Web/ExifOrientationUtilities.cs
src/ImageSharp.Web/ImageSharp.Web.csproj
src/ImageSharp.Web/Processors/ResizeWebProcessor.cs
src/ImageSharp.Web/TagHelpers/HmacTokenTagHelper.cs
src/ImageSharp.Web/TagHelpers/ImageTagHelper.cs
tests/ImageSharp.Web.Tests/Helpers/ExifOrientationUtilitiesTests.cs

- Fixes EXIF orientation utilities to correctly transform center coordinates.
- Updates ImageSharp to v3.1.5

Update refs and fix EXIF handling.

---

src/ImageSharp.Web/ImageCacheMetadata.cs
src/ImageSharp.Web/ImageSharp.Web.csproj
src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs

Updates ImageSharp to v3.1.8 and uses async disposal on relevant resources.

Update ImageSharp, dispose asynchronously

---

samples/ImageSharp.Web.Sample/Pages/Index.cshtml
src/ImageSharp.Web/FormatUtilities.cs
src/ImageSharp.Web/ImageSharp.Web.csproj
tests/ImageSharp.Web.Tests/Helpers/FormatUtilitiesTests.cs

Ensure invalid path extensions are skipped when validating input URLs

---

ImageSharp.Web.sln
SixLabors.ImageSharp.Web.props
samples/ImageSharp.Web.Sample/Pages/_ViewImports.cshtml

Fixes #389 
Reverses the behavior of our global includes to require an explicit <UseImageSharp>true</UseImageSharp> tag.
Breaking but I think necessary. We should have done this at the same time as https://github.com/SixLabors/ImageSharp/pull/2515

Make implicit global usings opt-in

---

.github/workflows/build-and-test.yml
README.md
src/ImageSharp.Web.Providers.AWS/Caching/AWSS3StorageCache.cs
src/ImageSharp.Web.Providers.AWS/ImageSharp.Web.Providers.AWS.csproj
src/ImageSharp.Web.Providers.AWS/Resolvers/AWSS3StorageCacheResolver.cs
src/ImageSharp.Web.Providers.AWS/Resolvers/AWSS3StorageImageResolver.cs
src/ImageSharp.Web.Providers.Azure/ImageSharp.Web.Providers.Azure.csproj
src/ImageSharp.Web/Middleware/ImageContext.cs
src/ImageSharp.Web/Middleware/ResponseConstants.cs
src/ImageSharp.Web/Providers/PhysicalFileSystemProvider.cs
tests/ImageSharp.Web.Tests/TestUtilities/AWSS3StorageImageProviderFactory.cs
tests/ImageSharp.Web.Tests/TestUtilities/ServerTestBase.cs

- Updates `AWSSDK.S3` to `4.0.6.2` Fixes #386
- Updates `Azure.Storage.Blobs` to `12.25.0`

Update dependencies and cleanup

---

src/ImageSharp.Web.Providers.Azure/Caching/AzureBlobStorageCache.cs
src/ImageSharp.Web.Providers.Azure/Caching/AzureBlobStorageCacheOptions.cs
src/ImageSharp.Web.Providers.Azure/Providers/AzureBlobStorageImageProvider.cs
src/ImageSharp.Web.Providers.Azure/Providers/AzureBlobStorageImageProviderOptions.cs
tests/ImageSharp.Web.Tests/TestUtilities/AzureBlobStorageImageProviderFactory.cs

Implementation of https://github.com/SixLabors/ImageSharp.Web/discussions/360

Feature: Added BlobContainerClientProvider option to AzureBlobStorageCache and AzureBlobStorageImageProvider

---

src/ImageSharp.Web.Providers.AWS/AmazonS3BucketClient.cs
src/ImageSharp.Web.Providers.AWS/AmazonS3ClientFactory.cs
src/ImageSharp.Web.Providers.AWS/Caching/AWSS3StorageCache.cs
src/ImageSharp.Web.Providers.AWS/Caching/AWSS3StorageCacheOptions.cs
src/ImageSharp.Web.Providers.AWS/IAWSS3BucketClientOptions.cs
src/ImageSharp.Web.Providers.AWS/Providers/AWSS3StorageImageProvider.cs
src/ImageSharp.Web.Providers.AWS/Providers/AWSS3StorageImageProviderOptions.cs
src/ImageSharp.Web.Providers.Azure/Caching/AzureBlobStorageCache.cs
src/ImageSharp.Web.Providers.Azure/Caching/AzureBlobStorageCacheOptions.cs
src/ImageSharp.Web.Providers.Azure/Providers/AzureBlobStorageImageProvider.cs
src/ImageSharp.Web.Providers.Azure/Providers/AzureBlobStorageImageProviderOptions.cs
tests/ImageSharp.Web.Tests/TestUtilities/AWSS3StorageCacheCacheFolderTestServerFixture.cs
tests/ImageSharp.Web.Tests/TestUtilities/AWSS3StorageCacheTestServerFixture.cs
tests/ImageSharp.Web.Tests/TestUtilities/AWSS3StorageImageProviderFactory.cs
tests/ImageSharp.Web.Tests/TestUtilities/ServerTestBase.cs

Following #361 and #362 
This PR does some API cleanup and fixes. Some of the changes are breaking but are required to fix an issue where Amazon clients were not disposed after use.

Fix, cleanup, and optimize new cloud provider code.
